/*
 * intern.h
 *
 * Global intern constants.
 *
 * (C) 2024, Kenneth Roe
 *
 * GNU Affero General Public License
 */
#ifndef REWLIB_INTERN_H
#define REWLIB_INTERN_H

#define INTERN_ORIENTED_RULE   1
#define INTERN_UNORIENTED_RULE 2
#define INTERN_BOOL            3
#define INTERN_TRUE            4
#define INTERN_FALSE           5
#define INTERN_UNIT            6
#define INTERN_IDENTITY        7
#define INTERN_TRIVIAL         8
#define INTERN_AND             9
#define INTERN_OR              10
#define INTERN_EQUAL           11
#define INTERN_PRECEQ          12
#define INTERN_DEFINED         13
#define INTERN_ALL             14
#define INTERN_EXISTS          15
#define INTERN_STAR            16
#define INTERN_NOT             17
#define INTERN_ITE             18
#define INTERN_UNDEF           19
#define INTERN_SET             20
#define INTERN_CONS            21
#define INTERN_NIL             22
#define INTERN_ATTR            23
#define INTERN_AC              24
#define INTERN_A               25
#define INTERN_C               26
#define INTERN_EPO             27
#define INTERN_EQ              28
#define INTERN_DERIVE          29
#define INTERN_TO              30
#define INTERN_ETO             31
#define INTERN_PO              32
#define INTERN_SMI             33
#define INTERN_CSMI            34
#define INTERN_OMI             35
#define INTERN_COMI            36
#define INTERN_SMD             37
#define INTERN_CSMD            38
#define INTERN_OMD             39
#define INTERN_COMD            40
#define INTERN_MI              41
#define INTERN_CMI             42
#define INTERN_MD              43
#define INTERN_CMD             44
#define INTERN_SOLVED          45
#define INTERN_T               46
#define INTERN_GOAL            47
#define INTERN_NODE            48
#define INTERN_BRANCH          49
#define INTERN_SUBTERM         50
#define INTERN_PATTERN         51
#define INTERN_DOWN            52
#define INTERN_TOP_GOAL        53
#define INTERN_TOP_NODE        54
#define INTERN_TOP_BRANCH      55
#define INTERN_TOP_SUBTERM     56
#define INTERN_TOP_PATTERN     57
#define INTERN_TOP_DOWN        58
#define INTERN_SUBGOALS        59
#define INTERN_DECOMP          60
#define INTERN_LESS            61
#define INTERN_PLUS            62
#define INTERN_SLASH           63
#define INTERN_PERCENT         64
#define INTERN_MINUS           65
#define INTERN_SIZE            66
#define INTERN_CHAR            67
#define INTERN_TOK_CHAR        67
#define INTERN_CONCAT          68
#define INTERN_CHR             69
#define INTERN_ASC             70
#define INTERN_DEF             71
#define INTERN_DEFAULT         72
#define INTERN_LAMBDA          73
#define INTERN_FN              74
#define INTERN_APPLY           75
#define INTERN_NAT_PLUS        76
#define INTERN_NAT_MINUS       77
#define INTERN_NAT_TIMES       78
#define INTERN_NAT_DIVIDE      79
#define INTERN_NAT_LESS        80
#define INTERN_NAT_MOD         81
#define INTERN_RAT_PLUS        82
#define INTERN_RAT_MINUS       83
#define INTERN_RAT_TIMES       84
#define INTERN_RAT_DIVIDE      85
#define INTERN_RAT_LESS        86
#define INTERN_RAT_MOD         87
#define INTERN_RAT_TO_NAT      88
#define INTERN_NAT_TO_RAT      89
#define INTERN_CASE            90
#define INTERN_INDEX           91
#define INTERN_OF              92
#define INTERN_DOUBLE_ARROW    93
#define INTERN_V               94
#define INTERN_TUPLE           95
#define INTERN_FUNCTION        96
#define INTERN_MEMBER          97
#define INTERN_UNION           98
#define INTERN_INTERSECT       99
#define INTERN_EF              100
#define INTERN_NE              101
#define INTERN_CS              102
#define INTERN_ACS             103
#define INTERN_RC              104
#define INTERN_QC              105
#define INTERN_QP              106
#define INTERN_AQC             107
#define INTERN_Q_NAT           108
#define INTERN_Q_RAT           109
#define INTERN_INT             110
#define INTERN_REAL            111
#define INTERN_STRING          112
#define INTERN_CAP_SET         113
#define INTERN_QUOTE           114
#define INTERN_QUANT           115
#define INTERN_APPL            116
#define INTERN_VAR             117
#define INTERN_QUESTION_MARK   118
#define INTERN_ONE_LINE_DIRECTIVE 119
#define INTERN_ONE_LINE_COMMENT   120
#define INTERN_START_DIRECTIVE 121
#define INTERN_START_COMMENT   122
#define INTERN_BACK_SLASH      123
#define INTERN_LEFT_PAREN      124
#define INTERN_RIGHT_PAREN     125
#define INTERN_LEFT_BRACKET    126
#define INTERN_RIGHT_BRACKET   127
#define INTERN_LEFT_BRACE      128
#define INTERN_RIGHT_BRACE     129
#define INTERN_COLON           130
#define INTERN_COMMA           131
#define INTERN_SQUOTE          132
#define INTERN_SEMICOLON       133
#define INTERN_SPACE_BAR       134
#define INTERN_INPUT           135
#define INTERN_OUTPUT          136
#define INTERN_MODE            137
#define INTERN_INFIX           138
#define INTERN_INFIX_MODE      139
#define INTERN_PERMIT          140
#define INTERN_BREAK           141
#define INTERN_MARK            142
#define INTERN_POUND           143
#define INTERN_FB              144
#define INTERN_FBM             145
#define INTERN_OB              146
#define INTERN_OBM             147
#define INTERN_RB              148
#define INTERN_RBM             149
#define INTERN_ML              150
#define INTERN_OL              151
#define INTERN_IDENTIFIER      152
#define INTERN_NATURAL         153
#define INTERN_CINT            154
#define INTERN_CCHAR           155
#define INTERN_CARRAY          156
#define INTERN_CFLEXARRAY      157
#define INTERN_CSTRUCT         158
#define INTERN_CUNION          159
#define INTERN_DPOINTER        160
#define INTERN_VPOINTER        161
#define INTERN_SPOINTER        162
#define INTERN_NPOINTER        163
#define INTERN_CCOMPLEMENT     164
#define INTERN_CUPLUS          165
#define INTERN_CPLUS           166
#define INTERN_CUMINUS         167
#define INTERN_CMINUS          168
#define INTERN_CTIMES          169
#define INTERN_CDIVIDE         170
#define INTERN_CMOD            171
#define INTERN_CAND            172
#define INTERN_COR             173
#define INTERN_CXOR            174
#define INTERN_CLAND           175
#define INTERN_CLOR            176
#define INTERN_CNOT            177
#define INTERN_CLSHIFT         178
#define INTERN_CRSHIFT         179
#define INTERN_CREF            180
#define INTERN_CSUB            181
#define INTERN_CDEREF          182
#define INTERN_CEQUAL          183
#define INTERN_CLESS           184
#define INTERN_CNOTEQUAL       185
#define INTERN_CGREATER        186
#define INTERN_CLESSEQUAL      187
#define INTERN_CGREATEREQUAL   188
#define INTERN_CASSIGN         189
#define INTERN_CPLUSASSIGN     190
#define INTERN_CMINUSASSIGN    191
#define INTERN_CTIMESASSIGN    192
#define INTERN_CDIVIDEASSIGN   193
#define INTERN_CMODASSIGN      194
#define INTERN_CANDASSIGN      195
#define INTERN_CORASSIGN       196
#define INTERN_CXORASSIGN      197
#define INTERN_CPREINCREMENT   198
#define INTERN_CPREDECREMENT   199
#define INTERN_CPOSTINCREMENT  200
#define INTERN_CPOSTDECREMENT  201
#define INTERN_CINDEX          202
#define INTERN_CALL            203
#define INTERN_CVAR            204
#define INTERN_CVARSTATE       205
#define INTERN_CSTACK          206
#define INTERN_CNAT            207
#define INTERN_CFLOAT          208
#define INTERN_CDOUBLE         209
#define INTERN_CSTRING         210
#define INTERN_CORE            211
#define INTERN_CPOINTER        212
#define INTERN_CGETFIELD       213
#define INTERN_CAST            214
#define INTERN_CSIZEOF         215
#define INTERN_CDECL           216
#define INTERN_CSTATICDECL     217
#define INTERN_CEXPR           218
#define INTERN_CBLOCK          219
#define INTERN_CIFELSE         220
#define INTERN_CWHILE          221
#define INTERN_CFOR            222
#define INTERN_CRETURN         223
#define INTERN_CPROC           224
#define INTERN_CGLOBAL         225
#define INTERN_CSTATIC         226
#define INTERN_CPRE            227
#define INTERN_CINVARIANT      228
#define INTERN_CLOAD           229
#define INTERN_CPOST           230
#define INTERN_CSTRUCTDECL     231
#define INTERN_CUNIONDECL      232
#define INTERN_CEXPORTVALID    233
#define INTERN_CINTDATUM       234
#define INTERN_CFLOATDATUM     235
#define INTERN_CCHARDATUM      236
#define INTERN_CSTRUCTDATUM    237
#define INTERN_CARRAYDATUM     238
#define INTERN_CPOINTERDATUM   239
#define INTERN_CTYPEDEF        240
#define INTERN_CLASS_DECL      241
#define INTERN_CCLASS_VARIABLE 242
#define INTERN_CCLASS_PROC     243
#define INTERN_CVIRTUAL        244
#define INTERN_CIF             245
#define INTERN_CLABEL          246
#define INTERN_CGOTO           247
#define INTERN_CLONG           248
#define INTERN_CSHORT          249
#define INTERN_CLONGLONG       250
#define INTERN_CUNSIGNED_CHAR  251
#define INTERN_CUNSIGNED_INT   252
#define INTERN_CUNSIGNED_LONG  253
#define INTERN_CUNSIGNED_LONG_LONG 254
#define INTERN_CUNSIGNED_SHORT 255
#define INTERN_CPOINTER_TYPE   256
#define INTERN_CCLASS          257
#define INTERN_GLOBAL          258
#define INTERN_LOCAL           259
#define INTERN_GETTYPE         260
#define INTERN_STACK           261
#define INTERN_STACK1          262
#define INTERN_STATE           263
#define INTERN_STATE1          264
#define INTERN_GETSTACK        265
#define INTERN_GETSTATE        266
#define INTERN_DISJOINT        267
#define INTERN_GLOBAL_LOC      268
#define INTERN_LOCAL_LOC       269
#define INTERN_GETVAL          270
#define INTERN_SIZEOF          271
#define INTERN_GETSTACK_NATURAL 272
#define INTERN_STRIP_STACK_NATURAL 273
#define INTERN_GETSTACK_RATIONAL 274
#define INTERN_STRIP_STACK_RATIONAL 275
#define INTERN_GETSTACK_STRING 276
#define INTERN_STRIP_STACK_STRING 277
#define INTERN_SNATURAL        278
#define INTERN_SRATIONAL       279
#define INTERN_SSTRING         280
#define INTERN_PRE             281
#define INTERN_LOOP            282
#define INTERN_COMPATIBLE_PREC 283
#define INTERN_MARKED_SUBSET   284
#define INTERN_INDUCE          285
#define INTERN_LOW             286
#define INTERN_NC_AND          287
#define INTERN_NC_OR           288
#define INTERN_CMODIFIES       289
#define INTERN_RETURN          290
#define INTERN_FIELD           291
#define INTERN_FIELD_NUM       292
#define INTERN_FIELD_TYPE      293
#define INTERN_CPROP           294
#define INTERN_CFUNCTION       295
#define INTERN_CDEF            296
#define INTERN_CTYPE           297
#define INTERN_CDEFORDER       298
#define INTERN_SUBSET          299
#define INTERN_FIELD_OFFSET    300
#define INTERN_GETGLOBALTYPE   301
#define INTERN_CPREC_LESS      302
#define INTERN_CMAX_PREC       303
#define INTERN_CEXTERN_PROC    304
#define INTERN_CEXTERN_VAR     305
#define INTERN_CFUNCTION_TYPE  306
#define INTERN_SETQ            307
#define INTERN_CNAME           308
#define INTERN_DIFFERENCE      309
#define INTERN_VALID_STATE     310
#define INTERN_CPROPP          311
#define INTERN_RCS             312
#define INTERN_SMALLER         313
#define INTERN_CUT             314
#define INTERN_PRIORITY        315
#define INTERN_MATCH_CLOSURE   316
#define INTERN_ANY_TYPE        317
#define INTERN_TEST_MATCH_CLOSURE 318
#define INTERN_SUBST           319
#define INTERN_FIRST_MATCH_CLOSURE 320
#define INTERN_REPLACE         321
#define INTERN_Q_VAR           322
#define INTERN_CHOOSE          323
#define INTERN_SPECIAL_REWRITES 324
#define INTERN_ANDQ            325
#define INTERN_SPECIAL_REWRITES_USING 326
#define INTERN_GET_CONTEXT_RULES 327
#define INTERN_MATCH           328
#define INTERN_INFERENCE       329
#define INTERN_NOTL            330
#define INTERN_ADD             331
#define INTERN_DELETE          332
#define INTERN_CHANGE          333
#define INTERN_CUT_LOCAL       334
#define INTERN_GET_TERMS       335
#define INTERN_GET_CURRENT_TERM 336
#define INTERN_UNQUANTIFY      337
#define INTERN_QUANTIFY        338
#define INTERN_UNQUOTE         339
#define INTERN_TYPE_CLOSURE    340
#define INTERN_FIRE_ON_CHANGE  341
#define INTERN_ILLEGAL_TERM    342
#define INTERN_NORMAL_CONDITION 343
#define INTERN_REWRITABLE      344
#define INTERN_EXCLUDE_SET     345
#define INTERN_APPLY_CONTEXT   346
#define INTERN_USE_CONTEXT     347
#define INTERN_EVAL_COND       348
#define INTERN_SIMPLIFY_COND   349
#define INTERN_MAIN_CONTEXT    350
#define INTERN_IN_CONTEXT      351
#define INTERN_BACKCHAIN       352
#define INTERN_ORDER_CACHE     353
#define INTERN_FORCE_ORIENTED  354
#define INTERN_MACRO_ARROW     355
#define INTERN_CMACRO          356
#define INTERN_BUILD_FUNCTOR   357
#define INTERN_NAT_TO_STRING   358
#define INTERN_APPEND          359
#define INTERN_MAP_SET         360
#define INTERN_AND_SET         361
#define INTERN_UNION_SET       362
#define INTERN_FILTER_SET      363
#define INTERN_SET_LIST        364
#define INTERN_LIST_SET        365
#define INTERN_OR_SET          366
#define INTERN_CURRENT_LEVEL   367
#define INTERN_MACRO_CONTEXT   368
#define INTERN_CASSERT         369
#define INTERN_CLOOP_INVARIANT 370
#define INTERN_POINTER_TO_NAT  371
#define INTERN_NAT_TO_POINTER  372
#define INTERN_GET_LIMIT_TERM  373
#define INTERN_CPREC_EQUAL     374
#define INTERN_NPO             375
#define INTERN_NEPO            376
#define INTERN_ANY_SUBTERM     377
#define INTERN_UNCOMPOSE       378
#define INTERN_CLOOP_LABEL     379
#define INTERN_SEPARATE        380
#define INTERN_IMPORTANT_STATE 381
#define INTERN_CHOOSE_CONTEXT_RULE 382
#define INTERN_KB_RULES        383
#define INTERN_CORDER          384
#define INTERN_CONTEXT         385
#define INTERN_NESTING_LIMIT   386
#define INTERN_PRUNE           387
#define INTERN_Q_UNUSED_VAR    388
#define INTERN_BLOCK_CONTEXT   389
#define INTERN_FIELD_SET       390
#define INTERN_MARK_VARS       391
#define INTERN_HAS_FREE_VARS   392
#define INTERN_CHECK_MODE      393
#define INTERN_CHECK_STATE     394
#define INTERN_CHECK_VALIDITY  395
#define INTERN_CHECK_VALIDITY_TERM 396
#define INTERN_FUNCTOR_ARGS    397
#define INTERN_IS_APPL         398
#define INTERN_ARG_COUNT       399
#define INTERN_CCMI            400
#define INTERN CCSMI           401
#define INTERN_CCMD            402
#define INTERN_CCSMD           403
#define INTERN_IS_FREE_IN      404
#define INTERN_REMOVE_AND      405
#define INTERN_CSTATE_CHECK    406
#define INTERN_C_MI            407
#define INTERN_C_MD            408
#define INTERN_C_SMI           409
#define INTERN_C_SMD           410
#define INTERN_USE_RULE        411
#define INTERN_VAR_AS_STRING   412
#define INTERN_TYPE_OF         413
#define INTERN_SPECIAL_TYPE    414
#define INTERN_EXPRESSION_TYPE 415
#define INTERN_TYPE            416
#define INTERN_MODULE          417
#define INTERN_INSTANCE        418
#define INTERN_CONNECT         419
#define INTERN_ASSIGN          420
#define INTERN_PARAMETER       421
#define INTERN_REG             422
#define INTERN_REG_VECTOR      423
#define INTERN_WIRE            424
#define INTERN_WIRE_VECTOR     425
#define INTERN_INPUT_VECTOR    426
#define INTERN_OUTPUT_VECTOR   427
#define INTERN_INOUT           428
#define INTERN_INOUT_VECTOR    429
#define INTERN_NOSPEC          430
#define INTERN_REFERENCE       431
#define INTERN_VEC_INDEX       432
#define INTERN_DELAY           433
#define INTERN_CURRENT         434
#define INTERN_PAR             435
#define INTERN_NEXT            436
#define INTERN_HEURISTIC       437
#define INTERN_NAT_POWER       438
#define INTERN_STATE_VAR       439
#define INTERN_NO_AUGMENT      440
#define INTERN_NO_FUNCTOR      441
#define INTERN_EDGE            442
#define INTERN_POSEDGE         443
#define INTERN_NEGEDGE         444
#define INTERN_CONDITION_EDGE  445
#define INTERN_CONDITION_ROOT  446
#define INTERN_CONDITION_VARIABLE 447
#define INTERN_SETSIZE         448
#define INTERN_SIGNAL_WIDTH    449
#define INTERN_SOLVE_FOR       450
#define INTERN_GCD             451
#define INTERN_NAT_MIN         452
#define INTERN_NAT_MAX         453
#define INTERN_NAT_INTEGRATE   454
#define INTERN_NAT_SOLVE_INTEGRATE 455
#define INTERN_NORMAL          456
#define INTERN_NAT_INTEGRATE_SET 457
#define INTERN_FD_DOM          458
#define INTERN_FD_MIN          459
#define INTERN_FD_MAX          460
#define INTERN_FD_FILLED       461
#define INTERN_FD_RANGE        462
#define INTERN_BITSEL          463
#define INTERN_BITPLUS         464
#define INTERN_BITCONST        465
#define INTERN_BITVEC          466
#define INTERN_BITNOT          467
#define INTERN_BITCAT          468
#define INTERN_LTRUE           469
#define INTERN_LFALSE          470
#define INTERN_READ            471
#define INTERN_WRITE           472
#define INTERN_BARRAY          473
#define INTERN_BIT             474
#define INTERN_LESS_EQUAL      475
#define INTERN_BICONDITIONAL   476
#define INTERN_XOR             477
#define INTERN_ARRAY           478
#define INTERN_UNKNOWN         479
#define INTERN_GREATER         480
#define INTERN_GREATER_EQUAL   481
#define INTERN_SLASH_EQUAL     482
#define INTERN_DOLLAR_SIGN     483
#define INTERN_SAT             484
#define INTERN_UNSAT           485
#define INTERN_TILDE           486
#define INTERN_STORE           487
#define INTERN_SELECT          488
#define INTERN_CAP_ARRAY       489
#define INTERN_U               490
#define INTERN_EE              491
#define INTERN_IFF             492
#define INTERN_QF_IDL          493
#define INTERN_QF_UF           494
#define INTERN_QF_UFIDL        495
#define INTERN_QF_RDL          496
#define INTERN_QF_LRA          497
#define INTERN_QF_LIA          498
#define INTERN_QF_UFLIA        499
#define INTERN_QF_UFBV32       500
#define INTERN_QF_AUFLIA       501
#define INTERN_AUFLIA          502
#define INTERN_AUFLIRA         503
#define INTERN_STRUCT_PRIMARY_POINTER 504
#define INTERN_INVARIANT       505
#define INTERN_STRUCT_SPACE    506
#define INTERN_IN              507
#define INTERN_DOTDOT          508
#define INTERN_PERIOD          509
#define INTERN_PATHSET         510
#define INTERN_PATHOR          511
#define INTERN_PATHSTAR        512
#define INTERN_BIT_OR          513
#define INTERN_TOK_UNSIGNED    514
#define INTERN_TOK_INT         515
#define INTERN_TOK_LONG        516
#define INTERN_TOK_SIGNED      517
#define INTERN_TOK_SHORT       518
#define INTERN_ATTRIBUTE       519
#define INTERN_CFUN            520
#define INTERN_CVOID           521
#define INTERN_TOK_VOID        522
#define INTERN_TOK_STRUCT      523
#define INTERN_TOK_CONST       524
#define INTERN_CBIT_FIELD      525
#define INTERN_CINT_TIMES_ASSIGN 526
#define INTERN_CINT_PLUS_ASSIGN 527
#define INTERN_CREF_ASSIGN     528
#define INTERN_CASSIGN_REF     529
#define INTERN_TOK_WHILE       530
#define INTERN_TOK_IF          531
#define INTERN_TOK_ELSE        532
#define INTERN_EXCP            533
#define INTERN_NOT_EQUAL       534
#define INTERN_TOK_EXTERN      535
#define INTERN_TOK_GOTO        536
#define INTERN_LDEF            537
#define INTERN_SIGMAPI         538

#endif

